spring.application.name=cookmate

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cookmate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=angrynison
spring.datasource.password=1m0057w9

# JPA-ddl
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT KEY
jwt.secret =
jwt.expiration-time = 3600000
